### ISSUE TITLE
Bakudo Teacher

### ISSUE THREAD

**Issue by Beosti** [Beosti/souls-awakening#12]
# Bakudo Teacher
## General Information
The Hado sub-genre of kido #9 has already gotten a teacher #5 , so it is normal for the Bakudo path to also get a teacher that takes care of those things
#### Quest start
The player gets the teleport positions of the teacher. Also can use the sai incantation.
#### Quest 
 The player has to use the incantation successfully on 5 different entities
#### Quest Reward
You can use Sai without Incantation
#### Quest start
Player gets nothing
#### Quest
Player has to use sai once on an entity while it is rope'd
#### Quest reward
You get the incantation and can cast the spell of hainawa
#### Quest start
Nothing
#### Quest
Use your shield 10 times against a physical attack without moving
#### Quest Reward
You get the spell "seki" and it's incantation

**Comment by DanielWaeraasUran** [comment]
Just like with hado there should be a higher level bakudo trainer (bakudo master fr fr) which teaches you the highest level bakudo spells, like the one he used to seal Aizen

**Comment by Beosti** [comment]
Did everything.
