### ISSUE TITLE
Mutation points/Hollow rework

### ISSUE THREAD

**Issue by Beosti** [Beosti/souls-awakening#13]
As for hollows I believe that there should be a sort of skill tree where as you eat hollows you get "mutation points" or something and get to choose what you want to specialize in, like faster cero charge, stronger hierro, faster regeneration, better sonido, etc. When a player gets to their arrancar phase they should keep the skill tree but be unable to gain more points without a big challenge first, like gaining segunda or a potential partial ressurreccion (like what Grimmjow showcased during the TYBW arc). 

This would both give hollows a way to progress outside of the basic hollow -> gillian -> adjuchas -> vasto lorde grind and a way to customize their playstyles and abilities a bit more to their liking.

_Originally posted by @DanielWaeraasUran in https://github.com/Beosti/souls-awakening/issues/4#issuecomment-2044223029_
            
# Mutation points/Hollow rework
## Explanation
The idea is that hollows get more choice in what they can "get good at" like the shinigami (and future quincy). Like we see in the show different hollows get their thing they're good at. Which at the moment, is not reflected in the mod. 
## How will it work?
Hollow points will stay the same and **will** stay the thing to make you evolve or not. But once evolving to arrancar **will** block their path of mutation points. Hollow points stay doable by just killing pluses (or shinigami), but mutation points will only be acquired through killing (mostly eating) other hollows.
## Points
This is very experimental but there will be a few things they can give points towards:
1. Reishi (cero bigger blast, faster recharge, more protection from kido spells etc.)
2. Resureccion (everything related to the resureccion ability, might be the reason they get a segunda etapa)
3. Constitution (overal max health + regeneration)
4. Hierro (More damage resistance from all coming sources + nullifying of damage)
5. Agility (speed, attack speed, everything around sonido)

This is still experimental!

**Comment by DanielWaeraasUran** [comment]
### List of cero variants I mean would be cool to have in the mod 

Cero Córnea: Cero beam shot from the eyes. Could give the user vision which is the colour of their reiatsu/reishi/whatever until they fire, other players and entities will either stay normal colour or be highlighted in some other way, activates either after a few second or on second activation of the ability.


Tounge Cero: Faster cero which shoots from the tounge. Just a faster cero which does slightly less damage.


Beautiful Charlotte Chuhlhourne's Final Holy Wonderful Pretty Super Magnum Sexy Sexy Glamorous Cero: Exclusive cero which is way cooler and way stronger than all the other ceros (Exclusive to me) (I want it) (I want it) (I want it) (Could also make it either patreon or tester exclusive)



### Criteria for Espada exclusive ceros (Oscuras and Gran Rey)
Unless you're adding an arrancar faction system to the mod I believe that gran rey cero and cero oscuras should be unlocked through the spirit and ressurreccion skill trees respectively.

Gran Rey Cero: 
Should be obtained through the cero skill tree, unlocking the skill in the skill tree will grant you a semi-challenging quest which lets you use gran rey cero by giving away around two hearts, if the user is already damaged (can be anywere from half health to a heart or two below max) it won't take the hearts.


Cero Oscuras:
Obtained either by becoming "strong enough" (do with that whatever you want) or unlocking it in the ressurreccion skill tree, could also have a quest tied to it. Cero Oscuras can only be used in ressurreccion.

**Comment by Beosti** [comment]
I like it, but at this moment I'll put it on the back burner this is pure polish for after a lot of it is done (trying to not do feature creep). Feel free to make a whole issue for it later down the line though.

**Comment by Beosti** [comment]
> Add defense as a path, since Nnoitra boasts about having the strongest hierro out of all the espada, you should be able to put points into increasing the strength of your hierro (gap in power between you the opponent before they can damage you, amount of damage reduction)

Remove the constitution thingy then, we're making it hierro and doing it like you said. I like it.

**Comment by DanielWaeraasUran** [comment]
> Remove the constitution thingy then, we're making it hierro and doing it like you said. I like it.
I was suggesting adding defense, not removing constitution.
There is a clear different between going for taking less damage and being able to heal the damage you take.
Healing damage may be a little harder to balance though if you have high speed regeneration, maybe you can have constitution locked behind a config?

**Comment by DanielWaeraasUran** [comment]
> > Remove the constitution thingy then, we're making it hierro and doing it like you said. I like it.

 I was suggesting adding defense, not removing constitution.
There is a clear different between going for taking less damage and being able to heal the damage you take.
Healing damage may be a little harder to balance though if you have high speed regeneration, maybe you can have constitution locked behind a config?

**Comment by Beosti** [comment]
Wait so you'd ADD hierro I thought replacing it, neh I like both tbh.
Hierro: reduce incoming damage
Constitution: higher max hp + regen

**Comment by DanielWaeraasUran** [comment]
> Wait so you'd ADD hierro I thought replacing it, neh I like both tbh. Hierro: reduce incoming damage Constitution: higher max hp + regen

Yes

**Comment by Beosti** [comment]
Constitution just adds more max health, passive hollow regen is already good enough (gets buffed when you evolve normally)
Hierro is fully added as expected
Reishi is added it just doesn't make the blast bigger but lower cooldown + more damage
Agility at this moment does nothing as there is a whole "hoho" system planned it'll fall under

**Comment by DanielWaeraasUran** [comment]
Just realized that hollows have no way to increase overall strength AND that they don't get overall stronger from evolving
