### ISSUE TITLE
General Shinigami Teacher Bugs

### ISSUE THREAD

**Issue by DanielWaeraasUran** [Beosti/souls-awakening#28]
# Bug 1
Shinigami teacher will turn you away if you've already crafted a zanpakudo before talking to one for the first time (You still become a shinigami by craftig a zanpakuto as a spirit)

# Bug 2
Shinigami teacher text box disappears around a second after he finishes speaking

![Image](https://github.com/Beosti/souls-awakening/assets/146202102/55e9a5d8-a563-4ff5-ab13-c19c002e1025)

# Bug 3
If you talk to the teacher after finishing your plus quest your game crashes

[crash-2024-04-21_09.42.16-client.txt](https://github.com/Beosti/souls-awakening/files/15051043/crash-2024-04-21_09.42.16-client.txt)

**Comment by Beosti** [comment]
Fixed :+1:
