### ISSUE TITLE
Soul Reaper soul society teleport ability bugs

### ISSUE THREAD

**Issue by DanielWaeraasUran** [Beosti/souls-awakening#30]
1: The cooldown is way longer than it should be, after some use of the calculator I figured you set it to 500 seconds instead of 500 ticks, since the cooldown is 10000 ticks (500 seconds) instead of 500 ticks (25 seconds), which is what the ability's description says is it's cooldown.

2: If you alt click again while it's on cooldown the cooldown resets

3: You lose it after you unlock shikai

**Comment by DanielWaeraasUran** [comment]
Added another bug to the list

**Comment by Beosti** [comment]
1. tl;dr cooldown is 10 times less now
2. Fixed
3. Fixed
