### ISSUE TITLE
Hollow agility points bug

### ISSUE THREAD

**Issue by DanielWaeraasUran** [Beosti/souls-awakening#32]
Agility points aren't going above 1 for hollows

![Image](https://github.com/Beosti/souls-awakening/assets/146202102/74e76527-a118-46fd-b411-c970245d0d28)

**Comment by Beosti** [comment]
Like, even with mutation points you can't make it above 1?

**Comment by Beosti** [comment]
Fixed

**Comment by DanielWaeraasUran** [comment]
> Like, even with mutation points you can't make it above 1?

Agility is the only thing that can't go above 1. 
Mutation points and can go above 1
