### ISSUE TITLE
Shinigami Teacher NPC

### ISSUE THREAD

**Issue by Beosti** [Beosti/souls-awakening#4]
# Teacher NPC
#### Kill a hollow
Get a zanpakuto and have to kill a hollow, once back you officially become a shinigami
#### Start
You get a zanpakuto in asauchi state
#### Reward
You officially become a shinigami
#### Rescue the pluses
First official mission as a shinigami, you have to bring 5 pluses to the soul society
#### Reward
You get officially on the gotei 13 and get money
#### Kill specific hollow
Kill a specific type of hollow that has been pestering people
#### Reward
Get money
#### Kill a menos 
You have to go out and find a menos to kill
#### Reward
Money
#### Rescue mission
Rescue a plus that has ended up in Hueco Mundo 
#### Reward
Money

**Comment by DanielWaeraasUran** [comment]
In addition to Hado, Bakudo and Shinigami teachers there should also be a hohō teacher which can teach you stuff like better flashsteps, shunko and air walk.

And alongside the hohō teacher there should be a kendo teacher which can teach you different sword skills.

**Comment by DanielWaeraasUran** [comment]
As for hollows I believe that there should be a sort of skill tree where as you eat hollows you get "mutation points" or something and get to choose what you want to specialize in, like faster cero charge, stronger hierro, faster regeneration, better sonido, etc. When a player gets to their arrancar phase they should keep the skill tree but be unable to gain more points without a big challenge first, like gaining segunda or a potential partial ressurreccion (like what Grimmjow showcased during the TYBW arc). 

This would both give hollows a way to progress outside of the basic hollow -> gillian -> adjuchas -> vasto lorde grind and a way to customize their playstyles and abilities a bit more to their liking.

**Comment by DanielWaeraasUran** [comment]
For the Kendo teacher, I believe that you can take inspiration from other anime.
There are also a few examples of Kendo in the bleach manga and anime, like Agitowari and Ryodan.

**Comment by Beosti** [comment]
> As for hollows I believe that there should be a sort of skill tree where as you eat hollows you get "mutation points" or something and get to choose what you want to specialize in, like faster cero charge, stronger hierro, faster regeneration, better sonido, etc. When a player gets to their arrancar phase they should keep the skill tree but be unable to gain more points without a big challenge first, like gaining segunda or a potential partial ressurreccion (like what Grimmjow showcased during the TYBW arc).
> 
> This would both give hollows a way to progress outside of the basic hollow -> gillian -> adjuchas -> vasto lorde grind and a way to customize their playstyles and abilities a bit more to their liking.

Ye imma make an issue for that, goated suggestion. At this moment it's just "hollow points" but calling it mutation points they can spend themselves like shinigami (or future quincy) would be cool.

**Comment by Beosti** [comment]
> For the Kendo teacher, I believe that you can take inspiration from other anime. There are also a few examples of Kendo in the bleach manga and anime, like Agitowari and Ryodan.
> 
> Also I completely forgot about Hakuda but it should be a requirement to finish a Hakuda trainer's quest and hoho trainer's quest to either get shunko, or the evolved version of a shunko

not sold imma keep it a buck

**Comment by DanielWaeraasUran** [comment]
> not sold imma keep it a buck

Imma be honest I was kinda cooked when writing that, but having kendo and hakuda skills would be nice, wouldn't necessarily need their own trainers but would be fun to have.

**Comment by DanielWaeraasUran** [comment]
> Ye imma make an issue for that, goated suggestion. At this moment it's just "hollow points" but calling it mutation points they can spend themselves like shinigami (or future quincy) would be cool.

I think letting the hollows choose a path for themselves like in the canon, either going for a balanced build or mostly focused on one to three abilities would be really intereseting and a different way of doing hollows from all the other bleach mods.
Being able to give up certain aspects like high speed regeneration for more strength or better hierro, while having given up your Pesquisa for better sonido or even an instant cero would give the hollows a unique system and keep closer to the canon. 
(I want to be a glass cannon while playing the mod)

**Comment by Beosti** [comment]
Did 3 Quests instead of 5, might reopen later but no feature creep for the time being.
