### ISSUE TITLE
Kido Teacher NPC

### ISSUE THREAD

**Issue by Beosti** [Beosti/souls-awakening#5]
# Kido/Hado Teacher NPC
### Learn the basics
You have to type out the full incantation of Sho to make it happen after 10 times you get the ability Sho and typing it empowers it
### Setup
You can do an incantation of Sho to make it happen
### Reward
You can now use sho in the scroll bar and can talk with other teachers for their version of kido, this teacher becomes the 'hado' path see #6 
### Learning Byakurai
Use Sho multiple times and use the incantation of Byakurai
### Reward
You can now use Byakurai in the scrolling wheel
### Learning Tsuzuri Raiden
Hold a 'metal' object while one shotting 10 entities
### Reward
You can now use Tsuzuri Raiden
### Learning Fushibi
The player has to kill multiple entities with 1 tnt block
### Reward
You learn Fushibi
### Learning Shakkaho
Kill 10 entities as last hit with Sho
### Reward
You can now use Shakkaho
### Learning Okasen
Kill 10 entities as last hit with Shakkaho while you have your zanpakuto in hand
### Reward
You can now use Okasen

**Comment by DanielWaeraasUran** [comment]
It would be interesting if you added a Kido Master which would teach you forbidden kido, modified kido and secret kido like Ittō Kasō, Jūgeki Byakurai, Goryūtenmetsu and Sannodō — Teppūsatsu.

**Comment by DanielWaeraasUran** [comment]
> It would be interesting if you added a Kido Master which would teach you forbidden kido, modified kido and secret kido like Ittō Kasō, Jūgeki Byakurai, Goryūtenmetsu and Sannodō — Teppūsatsu.

In addition to this there should be a hohō teacher so you can learn stuff like shunpo, shunko, etc.
The hohō trainer should also teach the ability to "air walk".

**Comment by Beosti** [comment]
Honestly goated suggestion, forbidden kido teacher will be a thing def expect an issue (post) about it. Same for secret kido (might be the same teacher). For modified kido I am not sure, I'd like to implement a modifed kido incantation system, but that's too time consuming compared to other shit I could do.

**Comment by Beosti** [comment]
Did 3 quests instead of 5. Good for the time being, no feature creep.
